spring:
  application:
    name: Tenpo

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tenpo}
    username: ${DB_USER:tenpo}
    password: ${DB_PASSWORD:tenpo123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: caffeine

server:
  port: 8080

external:
  percentage:
    value: 5
    failture-rate: 0.3
